# Site settings
title: Mark Rucker
email: rucker.mark@gmail.com
description: "Mark Rucker's personal website."
baseurl: ""
url: "http://markrucker.net"
twitter_username: 
github_username: mrucker 

# Build settings
markdown: kramdown
permalink: pretty
