# requires
#   sudo gem install jekyll-scholar 
#
# the site as it currently exists is using the built in syntax highlighting and no other extensions
# For the purposes of rendering equations the math_engine below is turned off and KaTeX is included
# as a JavaScript references in head.html for client side rendering. The syntax to being math blocks 
# for the KaTeX renderer can be found here (https://katex.org/docs/autorender.html).

# Site settings
title          : Mark Rucker
description    : "A little bit of this a little bit of that"
url            : "https://markrucker.net"
exclude        : ["README.md"]

# Collections
collections :
  posts:
    permalink: /musings/:title:output_ext
  areas:
    output: true
    permalink: /:name/
    order:
      - info.html
      - projects.html
      - articles.html
      - musings.html

# Defaults
defaults:
  - 
    scope:
      path: ""
    values:
      layout: "root"
  - 
    scope:
      path: ""
      type: "posts"
    values:
       layout: "post"
  - 
    scope:
      path: "assets/*"
    values:
      layout: "null"

# Personal info
email          : rucker.mark@gmail.com
github_username: mrucker 

# Jekyll settings
permalink: none
kramdown: 
  math_engine: #this actually needs to be blank, if you put the word 'nil' in place it breaks (Jekyll 4.0)
plugins:
  - jekyll-scholar

# sudo gem install jekyll-scholar 
scholar:
  style: ./_bibliography/my-ieee #I've added a space after the number in the references
