# Site settings
title: Mark Rucker
email: rucker.mark@gmail.com
description: "A little bit of this a little bit of that"
baseurl: ""
url: "http://markrucker.net"
twitter_username: 
github_username: mrucker 

# Build settings
markdown: kramdown
permalink: none
